### ISSUE TITLE
Android release builds not working

### ISSUE THREAD

**Issue by FlysoftBeta** [wusyong/cargo-mobile#131]
Got the following error after installing the release apk:

`adb logcat`
```
2023-04-08 17:31:36.756 19837-19837 AndroidRuntime          pid-19837                            E  FATAL EXCEPTION: main
                                                                                                    Process: com.flysoft.stock, PID: 19837
                                                                                                    java.lang.NoSuchMethodError: no non-static method "Lcom/flysoft/stock/RustWebView;.setAutoPlay(Z)V"
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:162)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8128)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
```
The `setAutoPlay` method is exist:
![image](https://user-images.githubusercontent.com/49718840/230716971-3885b326-1fdb-4c41-9bc4-a6726ca61709.png)

**Comment by FlysoftBeta** [comment]
Workaround: disable obfuscating.

**Comment by amrbashir** [comment]
Yes minifying and obfuscating would change this method name and `wry` won't be able to call it from rust. I will see if we can provide a proguard rules file for the methods that wry use.
