### ISSUE TITLE
cannot locate symbol "SSL_do_handshake" with successful build for android.

### ISSUE THREAD

**Issue by Zack-Xb** [wusyong/cargo-mobile#146]
**Describe the bug**
The tauri mobile application builds successfully but when trying to open it gets stuck, and also then gives the following error I think to do with openssl. 

**Steps To Reproduce**
Set up as tauri mobile app for android with vite-react.

- Dependencies
 ```
[dependencies]
tauri = { version = "2.0.0-alpha.8", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tiny-bip39 = "1.0.0"
rand = "0.8.5"
```

- Install openssl locally and fill the env variables as listed [here](https://github.com/tauri-apps/tauri-mobile/issues/144#issuecomment-1518684801) 

-run `cargo tauri android dev` to build.

**Expected behavior**
Opens the app successfully on android emulator.

**Error**
```
Performing Streamed Install
Success
Starting: Intent { cmp=com.tauri.availx/.MainActivity }
--------- beginning of main
04-24 16:46:41.131 14368 14368 I om.tauri.availx: Late-enabling -Xcheck:jni
04-24 16:46:41.289 14368 14368 W ziparchive: Unable to open '/data/app/~~NDuPBEDP_Uu2k1ji2kkQJw==/com.tauri.availx-mjsz4usMCkvP_SjhGvGvFA==/base.dm': No such file or directory
04-24 16:46:41.289 14368 14368 W ziparchive: Unable to open '/data/app/~~NDuPBEDP_Uu2k1ji2kkQJw==/com.tauri.availx-mjsz4usMCkvP_SjhGvGvFA==/base.dm': No such file or directory
--------- beginning of crash
04-24 16:46:41.388 14368 14368 E AndroidRuntime: FATAL EXCEPTION: main
04-24 16:46:41.388 14368 14368 E AndroidRuntime: Process: com.tauri.availx, PID: 14368
04-24 16:46:41.388 14368 14368 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "SSL_do_handshake" referenced by "/data/app/~~NDuPBEDP_Uu2k1ji2kkQJw==/com.tauri.availx-mjsz4usMCkvP_SjhGvGvFA==/base.apk!/lib/arm64-v8a/libavailx_lib.so"...
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1661)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at com.tauri.availx.TauriActivity.<clinit>(TauriActivity.kt:113)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1339)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3538)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-24 16:46:41.388 14368 14368 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
        Info Watching /Users/zack/SVC/Learn/tauri_try/availx/src-tauri for changes...
```

**Platform and Versions :**
Host OS:  MacOs Ventura 13.2.1
Target OS: aarch64-linux-android
Rustc:  1.68.2
Cargo: 1.68.2

**Comment by Zack-Xb** [comment]
Solved it, actually don't install openssl locally.

Add openssl = {version = "0.10.36", features = ["vendored"] } to dependencies.

Instead add RANLIB environment variable to here(https://github.com/tauri-apps/tauri-mobile/issues/144#issuecomment-1518684801).

Thank you and good evening.
