### ISSUE TITLE
Can't run example: The system cannot find the file specified

### ISSUE THREAD

**Issue by fr-an-k** [wusyong/cargo-mobile#199]
**Describe the bug**
The instructions to run on android lead to an error:

<details>

```
 (RT1) with target "aarch64-linux-android"

FAILURE: Build failed with an exception.

* What went wrong:
java.io.IOException: The system cannot find the file specified

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.UncheckedIOException: java.io.IOException: The system cannot find the file specified
        at org.gradle.internal.FileUtils.canonicalize(FileUtils.java:204)
        at org.gradle.initialization.layout.BuildLayoutFactory.layout(BuildLayoutFactory.java:89)
        at org.gradle.initialization.layout.BuildLayoutFactory.getLayoutFor(BuildLayoutFactory.java:77)
        at org.gradle.initialization.layout.BuildLayoutFactory.getLayoutFor(BuildLayoutFactory.java:40)
        at org.gradle.launcher.cli.converter.LayoutToPropertiesConverter.configureFromBuildDir(LayoutToPropertiesConverter.java:89)   
        at org.gradle.launcher.cli.converter.LayoutToPropertiesConverter.convert(LayoutToPropertiesConverter.java:67)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:223)      
        at org.gradle.launcher.Main.doAction(Main.java:35)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Caused by: java.io.IOException: The system cannot find the file specified
        at java.base/java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.base/java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:438)
        at java.base/java.io.File.getCanonicalPath(File.java:618)
        at java.base/java.io.File.getCanonicalFile(File.java:643)
        at org.gradle.internal.FileUtils.canonicalize(FileUtils.java:202)
        ... 22 more


* Get more help at https://help.gradle.org
error: Failed to assemble APK
    command ["\\\\?\\C:\\Users\\frank\\repos\\unovica_tauri\\gen\\android\\unovica_tauri\\gradlew.bat", "--project-dir",
    "\\\\?\\C:\\Users\\frank\\repos\\unovica_tauri\\gen\\android\\unovica_tauri"] exited with code 1
PS C:\Users\frank\repos\unovica_tauri> cargo android run --info
error: Found argument '--info' which wasn't expected, or isn't valid in this context

USAGE:
    cargo android run [FLAGS] [OPTIONS]

For more information try --help
```

</details>

Also, cargo mobile update fails with access denied (failed to move `C:\Users\frank\.cargo\bin\cargo-installuKcWEH\cargo-mobile.exe` to `C:\Users\frank\.cargo\bin\cargo-mobile.exe`), even in administrator mode.

**Steps To Reproduce**
mkdir unovica_tauri
cd unovica_tauri
cargo mobile init
cargo mobile run

(cargo mobile build succeeds but doesn't actually produce an APK)

**Expected behavior**
Instructions to run the example should work.

**Platform and Versions (please complete the following information):**
<details>

Host OS: Windows 11 (developer mode)
Target OS: Android AARCH64
Rustc: 1.72.0 (5680fa18f 2023-08-23)
`cargo mobile doctor`:
[✔] cargo-mobile v0.2.5
    • Contains commits up to "Update build.gradle.kts.hbs to fix Kotlin incorrect version usage (#122)"
    • Installed at "C:\\Users\\frank\\.tauri-mobile"
    • Windows 11 v10.0
    • rustc v1.72.0 (5680fa18f 2023-8-23)

[✔] Android developer tools
    • SDK v26.1.1 installed at "C:\\Users\\frank\\AppData\\Local\\Android\\Sdk"
    • NDK v25.2.9519653 installed at "C:\\Users\\frank\\AppData\\Local\\Android\\Sdk\\ndk\\25.2.9519653"

[✔] Connected devices
 (RT1)RT1
(if you build with specific commit, please list it as well)

</details>

**Would you want to assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Comment by amrbashir** [comment]
Your `tauri-mobile` installation is outdated, please do the following and try again:
1. remove `C:\Users\frank\.tauri-mobile` directory
2. `cargo install tauri-mobile --locked`
